### ISSUE TITLE
Show fees in all reports

### ISSUE THREAD

**Issue by manwithpowers** [rvola/woo-stripe-fee-in-report#1]
Is it possible to have the fees show up in all reports? Right now it only displays on the default 'Sales by date' report, not the 'Sales by product' or 'Sales by category' reports.
Happy to work on this myself if you can point me in the right direction.

**Comment by rvola** [comment]
Hello @manwithpowers 

Thank you for your request.
I do not think this is possible because we are not aware of Stripe Commissions by product.

It's like delivery costs, they are stored globally at the order.

Similarly in category, an order can contain several category products.

It is therefore not possible to deduce the commission figures.
The commission is related to the order, not the products.

**Comment by manwithpowers** [comment]
Understood, thanks for looking into it.
